version: '2.2'

services:
 rproxy:
    container_name: rproxy
    image: nginx:1.19.3
    restart: always
    ports:
      - "192.168.0.20:80:80"
      - "192.168.0.20:443:443"
    volumes:
      - /rproxy/etc/templates:/etc/nginx/templates
      - /rproxy/logs:/var/log/nginx
      - /rproxy/data/nginx/www:/var/www/nginx
      - /rproxy/data/certbot/conf:/etc/letsencrypt
      - /rproxy/data/certbot/www:/var/www/certbot
    environment:
      - TZ=Europe/Stockholm
      - NGINX_HOST=www.codebee.se
      - NGINX_HTTP_PORT=80
      - NGINX_HTTPS_PORT=443
 
 certbot:
    container_name: certbot
    image: certbot/certbot
    restart: "no"
    volumes:
      - /rproxy/data/certbot/conf:/etc/letsencrypt
      - /rproxy/data/certbot/www:/var/www/certbot
      - /rproxy/logs/certbot/letsencrypt:/var/log/letsencrypt
#   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    entrypoint: "/bin/sh -c 'certbot renew'"

